package com.example.roadsigns

import com.example.roadsigns.models.SignModel

class LoadSigns {

    fun loadSigns() : ArrayList<SignModel>{
        val signs = arrayListOf(
            SignModel(R.drawable.stop_back, "Stop from back", true ),
            SignModel(R.drawable.stop_front, "Stop from front", true),
            SignModel(R.drawable.stop_front_back, "Stop from front and back", true),
            SignModel(R.drawable.go_front, "Go from front", true),
            SignModel(R.drawable.go_back, "Go from back", true),
            SignModel(R.drawable.go_side, "Go from side road", true),
            SignModel(R.drawable.intend_slow_or_stop, "Intend to SLOW DOWN or STOP", false),
            SignModel(R.drawable.intend_move_right, "Intend to MOVE TO THE RIGHT", false),
            SignModel(R.drawable.intend_turn_left, "Intend to MOVE TO THE LEFT or TURN LEFT", false),

            SignModel(R.drawable.bend_left, "Dangerous bend to the left", false),
            SignModel(R.drawable.bend_right, "Dangerous bend to the right", false),
            SignModel(R.drawable.multiple_bend_first_left, "Multiple bends first to the left", false),
            SignModel(R.drawable.multiple_bend_first_right, "Multiple bends first to the right", false),
            SignModel(R.drawable.hump, "Road hump", false),
            SignModel(R.drawable.steep_hill_downwards, "Steep hill downwards", false),
            SignModel(R.drawable.steep_hill_upwards, "Steep hill upwards", false),
            SignModel(R.drawable.fallen_rock, "Fallen rock", false),
            SignModel(R.drawable.slippery_road, "Slippery road", false),
            SignModel(R.drawable.uneven_road, "Uneven road", false),
            SignModel(R.drawable.loose_surface, "Loose surface", false),
            SignModel(R.drawable.road_narrows_both_sides, "Road narrows both sides", false),
            SignModel(R.drawable.road_narrows_left, "Road narrows on the left", false),
            SignModel(R.drawable.road_narrows_right, "Road narrows on the right", false),

            SignModel(R.drawable.road_works, "Road works ahead", false ),
            SignModel(R.drawable.children, "Frequent use of road by children", false ),
            SignModel(R.drawable.two_way_traffic, "Two way traffic", false ),
            SignModel(R.drawable.two_way_traffic_cross, "Two way traffic crosses one-way road", false ),
            SignModel(R.drawable.other_dangers, "Other dangers", false ),
            SignModel(R.drawable.junction1, "Junction with secondary roads", true ),
            SignModel(R.drawable.junction2, "Junction with secondary roads", true ),
            SignModel(R.drawable.junction3, "Junction with secondary roads", true ),
            SignModel(R.drawable.junction4, "Junction with secondary roads", true ),
            SignModel(R.drawable.junction5, "Junction with secondary roads", true ),
            SignModel(R.drawable.junction6, "Junction with secondary roads", true ),

            SignModel(R.drawable.junction_priority_right, "Junction where priority have cars from the RIGHT", false ),
            SignModel(R.drawable.roundabout, "Roundabout", false ),
            SignModel(R.drawable.warning_distance, "Give way in 200m", false ),
            SignModel(R.drawable.warning_stop, "Give way. You have stop in 50m", false ),
            SignModel(R.drawable.priority_opposite, "Priority for vehicles coming from OPPOSITE directions", false ),
            SignModel(R.drawable.priority_you, "Priority to traffic in YOUR directions", false ),
            SignModel(R.drawable.give_way, "Give way", true ),
            SignModel(R.drawable.stop, "STOP", true ),
            SignModel(R.drawable.priority, "Road with priority", true ),
            SignModel(R.drawable.priority_end, "End of road with priority", true ),
            SignModel(R.drawable.controlled_crossing1, "Junction with control", false ),
            SignModel(R.drawable.not_controlled_crossing, "Junction without control", false ),
            SignModel(R.drawable.not_controlled_2, "Junction without control", false ),
            SignModel(R.drawable.distance_to_junction, "Distance to the junction (300 - 200 - 100m)", true ),

            SignModel(R.drawable.no_entry, "No ENTRY", false ),
            SignModel(R.drawable.closed_to_all, "Road closed to all traffic in both directions", true ),
            SignModel(R.drawable.no_cars, "No entry for all vehicles except two wheeled motor cycles", false ),
            SignModel(R.drawable.no_motor_cycles, "No entry for motor cycles", false ),
            SignModel(R.drawable.no_auto_cycles, "No entry for auto cycles", false ),
            SignModel(R.drawable.no_pedestrians, "No crossing for pedestrians", false ),
            SignModel(R.drawable.no_turn_left, "No turn left", false ),
            SignModel(R.drawable.no_turn_right, "No turn right", false ),
            SignModel(R.drawable.no_u_turns, "No U turns", false ),
            SignModel(R.drawable.no_motor_vehicles, "No mechanically propelled vehicles through", true ),
            SignModel(R.drawable.no_overtaking, "No overtaking", true ),
            SignModel(R.drawable.no_tons, "No vehicles in excess of 7 tons through", false ),
            SignModel(R.drawable.width, "No vehicles more than 2.3m wide", false ),
            SignModel(R.drawable.max_height, "No vehicles more than 3.5m in height", false ),

            SignModel(R.drawable.max_speed_limit, "Maximum speed", false ),
            SignModel(R.drawable.end_overtaking_prohib, "End of overtaking prohibition (You can overtake)", false ),
            SignModel(R.drawable.end_all_prohib, "End of all prohibitions", false ),
            SignModel(R.drawable.end_speed_limit, "End speed limit (Yo can move more than 50)", false ),
            SignModel(R.drawable.keep_left, "Keep left", false ),
            SignModel(R.drawable.keep_right, "Keep right", false ),
            SignModel(R.drawable.turn_left_ahead, "Turn left ahead", false ),
            SignModel(R.drawable.turn_right_ahead, "Turn right ahead", false ),
            SignModel(R.drawable.compulsory_chains, "Compulsory use of wheel chains", false ),
            SignModel(R.drawable.compulsory_roundabout, "Compulsory roundabout", false ),
            SignModel(R.drawable.compulsory_speed, "Compulsory minimum speed limit", false ),
            SignModel(R.drawable.dir_left, "Go left", false ),
            SignModel(R.drawable.dir_straight, "Go ahead", false ),
            SignModel(R.drawable.rid_righr, "Go right", false ),
            SignModel(R.drawable.go_straight_or_left, "Go straight or left", false ),
            SignModel(R.drawable.go_straight_or_right, "Go straight or right", false ),

            SignModel(R.drawable.dead_end, "Dead end road (No way through)", false ),
            SignModel(R.drawable.one_wa1, "One-way road", false ),
            SignModel(R.drawable.one_way2, "One-way road", false ),
            SignModel(R.drawable.motorway, "Motorway", false ),
            SignModel(R.drawable.end_motorway, "End of motorway", false ),

            SignModel(R.drawable.no_parking, "No parking", true ),
            SignModel(R.drawable.no_stop_and_parking, "No parking and waiting", true ),
            SignModel(R.drawable.no_parking_odd, "Parking prohibited ODD dates", true ),
            SignModel(R.drawable.no_parking_even, "Parking prohibited EVEN dates", true ),
            SignModel(R.drawable.parking_limited, "Yes you can park limited time (restricted duration)", true ),
        )
        return signs
    }
}