package com.example.roadsigns

import com.example.roadsigns.models.SignModel

class LoadSigns {

    fun loadSigns() : ArrayList<SignModel>{
        val signs = arrayListOf(
            SignModel(R.drawable.stop_back, "Stop from back", true ),
            SignModel(R.drawable.stop_front, "Stop from front", true),
            SignModel(R.drawable.stop_front_back, "Stop from front and back", true),
            SignModel(R.drawable.go_front, "Go from front", true),
            SignModel(R.drawable.go_back, "Go from back", true),
            SignModel(R.drawable.go_side, "Go from side road", true),
            SignModel(R.drawable.intend_slow_or_stop, "Intend to SLOW DOWN or STOP", false),
            SignModel(R.drawable.intend_move_right, "Intend to MOVE TO THE RIGHT", false),
            SignModel(R.drawable.intend_turn_left, "Intend to MOVE TO THE LEFT or TURN LEFT", false),

            SignModel(R.drawable.bend_left, "Dangerous bend to the left", false),
            SignModel(R.drawable.bend_right, "Dangerous bend to the right", false),
            SignModel(R.drawable.multiple_bend_first_left, "Multiple bends first to the left", false),
            SignModel(R.drawable.multiple_bend_first_right, "Multiple bends first to the right", false),
            SignModel(R.drawable.hump, "Road hump", false),
            SignModel(R.drawable.steep_hill_downwards, "Steep hill downwards", false),
            SignModel(R.drawable.steep_hill_upwards, "Steep hill upwards", false),
            SignModel(R.drawable.fallen_rock, "Fallen rock", false),
            SignModel(R.drawable.slippery_road, "Slippery road", false),
            SignModel(R.drawable.uneven_road, "Uneven road", false),
            SignModel(R.drawable.loose_surface, "Loose surface", false),
            SignModel(R.drawable.road_narrows_both_sides, "Road narrows both sides", false),
            SignModel(R.drawable.road_narrows_left, "Road narrows on the left", false),
            SignModel(R.drawable.road_narrows_right, "Road narrows on the right", false),

            SignModel(R.drawable.road_works, "Road works ahead", false ),
            SignModel(R.drawable.children, "Frequent use of road by children", false ),
            SignModel(R.drawable.two_way_traffic, "Two way traffic", false ),
            SignModel(R.drawable.two_way_traffic_cross, "Two way traffic crosses one-way road", false ),
            SignModel(R.drawable.other_dangers, "Other dangers", false ),
            SignModel(R.drawable.junction1, "Junction with secondary roads", true ),
            SignModel(R.drawable.junction2, "Junction with secondary roads", true ),
            SignModel(R.drawable.junction3, "Junction with secondary roads", true ),
            SignModel(R.drawable.junction4, "Junction with secondary roads", true ),
            SignModel(R.drawable.junction5, "Junction with secondary roads", true ),
            SignModel(R.drawable.junction6, "Junction with secondary roads", true ),

            SignModel(R.drawable.junction_priority_right, "Junction where priority have cars from the RIGHT", false ),
            SignModel(R.drawable.roundabout, "Roundabout", false ),
            SignModel(R.drawable.warning_distance, "Give way in 200m", false ),
            SignModel(R.drawable.warning_stop, "Give way. You have stop in 50m", false ),
            SignModel(R.drawable.priority_opposite, "Priority for vehicles coming from OPPOSITE directions", false ),
            SignModel(R.drawable.priority_you, "Priority to traffic in YOUR directions", false ),
            SignModel(R.drawable.give_way, "Give way", true ),
            SignModel(R.drawable.stop, "STOP", true ),
            SignModel(R.drawable.priority, "Road with priority", true ),
            SignModel(R.drawable.priority_end, "End of road with priority", true ),
            SignModel(R.drawable.controlled_crossing1, "Junction with control", false ),
            SignModel(R.drawable.not_controlled_crossing, "Junction without control", false ),
            SignModel(R.drawable.not_controlled_2, "Junction without control", false ),
            SignModel(R.drawable.distance_to_junction, "Distance to the junction (300 - 200 - 100m)", true ),

            SignModel(R.drawable.no_entry, "No ENTRY", false ),
            SignModel(R.drawable.closed_to_all, "Road closed to all traffic in both directions", true ),
            SignModel(R.drawable.no_cars, "No entry for all vehicles except two wheeled motor cycles", false ),
            SignModel(R.drawable.no_motor_cycles, "No entry for motor cycles", false ),
            SignModel(R.drawable.no_auto_cycles, "No entry for auto cycles", false ),
            SignModel(R.drawable.no_pedestrians, "No crossing for pedestrians", false ),
            SignModel(R.drawable.no_turn_left, "No turn left", false ),
            SignModel(R.drawable.no_turn_right, "No turn right", false ),
            SignModel(R.drawable.no_u_turns, "No U turns", false ),
            SignModel(R.drawable.no_motor_vehicles, "No mechanically propelled vehicles through", true ),
            SignModel(R.drawable.no_overtaking, "No overtaking", true ),
            SignModel(R.drawable.no_tons, "No vehicles in excess of 7 tons through", false ),
            SignModel(R.drawable.width, "No vehicles more than 2.3m wide", false ),
            SignModel(R.drawable.max_height, "No vehicles more than 3.5m in height", false ),

            SignModel(R.drawable.max_speed_limit, "Maximum speed", false ),
            SignModel(R.drawable.end_overtaking_prohib, "End of overtaking prohibition (You can overtake)", false ),
            SignModel(R.drawable.end_all_prohib, "End of all prohibitions", false ),
            SignModel(R.drawable.end_speed_limit, "End speed limit (Yo can move more than 50)", false ),
            SignModel(R.drawable.keep_left, "Keep left", false ),
            SignModel(R.drawable.keep_right, "Keep right", false ),
            SignModel(R.drawable.turn_left_ahead, "Turn left ahead", false ),
            SignModel(R.drawable.turn_right_ahead, "Turn right ahead", false ),
            SignModel(R.drawable.compulsory_chains, "Compulsory use of wheel chains", false ),
            SignModel(R.drawable.compulsory_roundabout, "Compulsory roundabout", false ),
            SignModel(R.drawable.compulsory_speed, "Compulsory minimum speed limit", false ),
            SignModel(R.drawable.dir_left, "Go left", false ),
            SignModel(R.drawable.dir_straight, "Go ahead", false ),
            SignModel(R.drawable.rid_righr, "Go right", false ),
            SignModel(R.drawable.go_straight_or_left, "Go straight or left", false ),
            SignModel(R.drawable.go_straight_or_right, "Go straight or right", false ),

            SignModel(R.drawable.dead_end, "Dead end road (No way through)", false ),
            SignModel(R.drawable.one_way2, "One-way road", false ),
            SignModel(R.drawable.motorway, "Motorway", false ),
            SignModel(R.drawable.end_motorway, "End of motorway", false ),

            SignModel(R.drawable.no_parking, "No parking", true ),
            SignModel(R.drawable.no_stop_and_parking, "No parking and waiting", true ),
            SignModel(R.drawable.no_parking_odd, "Parking prohibited ODD dates", true ),
            SignModel(R.drawable.no_parking_even, "Parking prohibited EVEN dates", true ),
            SignModel(R.drawable.parking_limited, "Yes you can park limited time (restricted duration)", true ),


            SignModel(R.drawable.hump_bridge, "Hump bridge", false ),
            SignModel(R.drawable.junction_bend_ahead1, "Junction on bend ahead", false ),
            SignModel(R.drawable.junction_bend_ahead2, "Junction on bend ahead", false ),
            SignModel(R.drawable.pedestrians_ahead, "Pedestrians in road ahead", false ),
            SignModel(R.drawable.airport, "Airport (low flying planes)", false ),
            SignModel(R.drawable.traffic_jam, "Traffic queues likely ahead", false ),
            SignModel(R.drawable.pedestrian_crossing, "Pedestrians crossing", false ),
            SignModel(R.drawable.soft_road_right, "Soft road left (verge on the left)", false ),
            SignModel(R.drawable.soft_road_left, "Soft road right (verge on the right)", false ),
            SignModel(R.drawable.tunnel, "Tunnel ahead", false ),
            SignModel(R.drawable.electric_cable, "Overhead electric cable", false ),
            SignModel(R.drawable.risk_of_ice, "Risk of ice", false ),
            SignModel(R.drawable.dual_carriegeway, "2 roads become 1 (Dual carriageway ends)", false ),
            SignModel(R.drawable.one_wa1, "One-way road", false ),

            SignModel(R.drawable.compulsory_left_turn, "Compulsory left turn", false ),
            SignModel(R.drawable.compulsory_right_turn, "Compulsory right turn", false ),
            SignModel(R.drawable.compulsory_turn_both, "Compulsory turn from left or right", false ),
            SignModel(R.drawable.box_junction, "Box junction (Controlled square crossing). Enter the square when you intend to turn right", true ),
            SignModel(R.drawable.humper_crossing, "Humped crossing", false ),
            SignModel(R.drawable.warning_school, "Warning signs in schools", false ),


            SignModel(R.drawable.residental_end, "End residential area (users don't have equal priority)", false ),
            SignModel(R.drawable.resid, "Residential area (users have equal priority)", false ),
            SignModel(R.drawable.overpass, "Overpass", false ),
            SignModel(R.drawable.underpass, "Underpass", false ),
            SignModel(R.drawable.underpass_ramp, "Underpass with ramp", false ),
            SignModel(R.drawable.pedestrian_blue, "Pedestrian crossing", false ),
            SignModel(R.drawable.speed_road, "Speed road", false ),
            SignModel(R.drawable.end_speed_road, "End of speed road", false ),

            SignModel(R.drawable.broken_line, "You can overtake", false ),
            SignModel(R.drawable.one_line, "No overtaking", false ),
            SignModel(R.drawable.two_lines, "No overtaking", false ),
            SignModel(R.drawable.broken_left, "Overtaking from left (broken side)", false ),
            SignModel(R.drawable.broken_right, "Overtaking from right (broken side)", false ),
            SignModel(R.drawable.zig_zag, "No overtaking, no parking alongside", false ),
            SignModel(R.drawable.double_yellow, "No stop, no parking", false ),
            SignModel(R.drawable.one_yellow, "No parking", false ),
            SignModel(R.drawable.broken_side, "Bus stop", false ),
            SignModel(R.drawable.road_lines, "This part of road must not used by vehicles", false ),
            SignModel(R.drawable.road_lines2, "This part of road must not used by vehicles", false ),
            SignModel(R.drawable.change_directions, "Change direction in 200 m", false ),
            SignModel(R.drawable.reduce_lines, "Reduce number of lanes in 600m", false ),
            SignModel(R.drawable.gray_sircle, "Cycle in small roundabout (разметка)", false ),

            SignModel(R.drawable.ped_cross, "Pedestrians crossing", false ),
            SignModel(R.drawable.pedal_cyclist, "Road used by pedal cyclists", false ),
            SignModel(R.drawable.ditch, "Ditch", false )
            )
        return signs
    }


    fun loadMixedSigns() : ArrayList<SignModel>{
            val mixedSigns = arrayListOf(
                SignModel(2131165384, "Multiple bends first to the left", false),
        SignModel(2131165464, "No overtaking", false),
        SignModel(2131165351, "Keep right", false),
        SignModel(2131165297, "Junction with control", false),
        SignModel(2131165308, "No stop, no parking", false),
        SignModel(2131165445, "Slippery road", false),
        SignModel(2131165399, "No turn left", false),
        SignModel(2131165430, "Priority for vehicles coming from OPPOSITE directions", false),
        SignModel(2131165403, "Junction without control", false),
        SignModel(2131165428, "Road with priority", true),
        SignModel(2131165395, "Parking prohibited ODD dates", true),
        SignModel(2131165348, "Junction on bend ahead", false),
        SignModel(2131165389, "No ENTRY", false),
        SignModel(2131165372, "Maximum speed", false),
        SignModel(2131165443, "Roundabout", false),
        SignModel(2131165278, "Overtaking from right (broken side)", false),
        SignModel(2131165473, "No vehicles more than 2.3m wide", false),
        SignModel(2131165342, "Junction with secondary roads", true),
        SignModel(2131165305, "Go ahead", false),
        SignModel(2131165472, "Give way. You have stop in 50m", false),
        SignModel(2131165425, "Pedestrian crossing", false),
        SignModel(2131165469, "Uneven road", false),
        SignModel(2131165304, "Go left", false),
        SignModel(2131165421, "Overpass", false),
        SignModel(2131165298, "Dead end road (No way through)", false),
        SignModel(2131165468, "Underpass with ramp", false),
        SignModel(2131165296, "Compulsory turn from left or right", false),
        SignModel(2131165466, "Two way traffic crosses one-way road", false),
        SignModel(2131165343, "Junction with secondary roads", true),
        SignModel(2131165385, "Multiple bends first to the right", false),
        SignModel(2131165347, "Junction on bend ahead", false),
        SignModel(2131165446, "Soft road right (verge on the right)", false),
        SignModel(2131165418, "One-way road", false),
        SignModel(2131165417, "One-way road", false),
        SignModel(2131165350, "Keep left", false),
        SignModel(2131165315, "End of speed road", false),
        SignModel(2131165441, "Road narrows on the right", false),
        SignModel(2131165320, "Go from side road", true),
        SignModel(2131165319, "Go from front", true),
        SignModel(2131165310, "Overhead electric cable", false),
        SignModel(2131165338, "Intend to MOVE TO THE RIGHT", false),
        SignModel(2131165275, "Box junction (Controlled square crossing). Enter the square when you intend to turn right", true),
        SignModel(2131165470, "Give way in 200m", false),
        SignModel(2131165373, "Motorway", false),
        SignModel(2131165453, "Stop from back", true),
        SignModel(2131165270, "Airport (low flying planes)", false),
        SignModel(2131165317, "Give way", true),
        SignModel(2131165429, "End of road with priority", true),
        SignModel(2131165394, "Parking prohibited EVEN dates", true),
        SignModel(2131165292, "Compulsory left turn", false),
        SignModel(2131165451, "Steep hill upwards", false),
        SignModel(2131165276, "Overtaking from left (broken side)", false),
        SignModel(2131165442, "Road works ahead", false),
        SignModel(2131165273, "Dangerous bend to the left", false),
        SignModel(2131165288, "Change direction in 200 m", false),
        SignModel(2131165307, "Ditch", false),
        SignModel(2131165318, "Go from back", true),
        SignModel(2131165346, "Junction with secondary roads", true),
        SignModel(2131165401, "No U turns", false),
        SignModel(2131165447, "Soft road left (verge on the left)", false),
        SignModel(2131165309, "2 roads become 1 (Dual carriageway ends)", false),
        SignModel(2131165341, "Junction with secondary roads", true),
        SignModel(2131165471, "Warning signs in schools", false),
        SignModel(2131165462, "Turn left ahead", false),
        SignModel(2131165390, "No entry for motor cycles", false),
        SignModel(2131165316, "Fallen rock", false),
        SignModel(2131165420, "Other dangers", false),
        SignModel(2131165352, "Loose surface", false),
        SignModel(2131165340, "Intend to MOVE TO THE LEFT or TURN LEFT", false),
        SignModel(2131165397, "No parking and waiting", true),
        SignModel(2131165279, "Bus stop", false),
        SignModel(2131165313, "End of overtaking prohibition (You can overtake)", false),
        SignModel(2131165467, "Underpass", false),
        SignModel(2131165433, "Residential area (users have equal priority)", false),
        SignModel(2131165311, "End of all prohibitions", false),
        SignModel(2131165326, "Humped crossing", false),
        SignModel(2131165450, "Steep hill downwards", false),
        SignModel(2131165398, "No vehicles in excess of 7 tons through", false),
        SignModel(2131165349, "Junction where priority have cars from the RIGHT", false),
        SignModel(2131165324, "Road hump", false),
        SignModel(2131165325, "Hump bridge", false),
        SignModel(2131165426, "Pedestrians crossing", false),
        SignModel(2131165388, "No entry for all vehicles except two wheeled motor cycles", false),
        SignModel(2131165293, "Compulsory right turn", false),
        SignModel(2131165323, "Cycle in small roundabout (разметка)", false),
        SignModel(2131165454, "Stop from front", true),
        SignModel(2131165392, "No overtaking", true),
        SignModel(2131165434, "End residential area (users don't have equal priority)", false),
        SignModel(2131165294, "Compulsory roundabout", false),
        SignModel(2131165290, "Road closed to all traffic in both directions", true),
        SignModel(2131165438, "This part of road must not used by vehicles", false),
        SignModel(2131165416, "No overtaking", false),
        SignModel(2131165460, "Traffic queues likely ahead", false), SignModel(2131165400, "No turn right", false),
        SignModel(2131165427, "Pedestrians in road ahead", false),
        SignModel(2131165424, "Road used by pedal cyclists", false),
        SignModel(2131165387, "No entry for auto cycles", false),
        SignModel(2131165465, "Two way traffic", false),
        SignModel(2131165431, "Priority to traffic in YOUR directions", false),
        SignModel(2131165345, "Junction with secondary roads", true),
        SignModel(2131165391, "No mechanically propelled vehicles through", true),
        SignModel(2131165423, "Pedestrians crossing", false),
        SignModel(2131165437, "This part of road must not used by vehicles", false),
        SignModel(2131165455, "Stop from front and back", true),
        SignModel(2131165432, "Reduce number of lanes in 600m", false),
        SignModel(2131165321, "Go straight or left", false),
        SignModel(2131165371, "No vehicles more than 3.5m in height", false),
        SignModel(2131165452, "STOP", true),
        SignModel(2131165440, "Road narrows on the left", false),
        SignModel(2131165461, "Tunnel ahead", false),
        SignModel(2131165291, "Compulsory use of wheel chains", false),
        SignModel(2131165396, "No crossing for pedestrians", false),
        SignModel(2131165277, "You can overtake", false),
        SignModel(2131165419, "No parking", false),
        SignModel(2131165295, "Compulsory minimum speed limit", false),
        SignModel(2131165393, "No parking", true),
        SignModel(2131165344, "Junction with secondary roads", true),
        SignModel(2131165402, "Junction without control", false),
        SignModel(2131165474, "No overtaking, no parking alongside", false),
        SignModel(2131165339, "Intend to SLOW DOWN or STOP", false),
        SignModel(2131165322, "Go straight or right", false),
        SignModel(2131165314, "End speed limit (Yo can move more than 50)", false),
        SignModel(2131165463, "Turn right ahead", false),
        SignModel(2131165306, "Distance to the junction (300 - 200 - 100m)", true),
        SignModel(2131165435, "Go right", false),
        SignModel(2131165449, "Speed road", false),
        SignModel(2131165312, "End of motorway", false),
        SignModel(2131165436, "Risk of ice", false),
        SignModel(2131165422, "Yes you can park limited time (restricted duration)", true),
        SignModel(2131165439, "Road narrows both sides", false),
        SignModel(2131165274, "Dangerous bend to the right", false),
        SignModel(2131165289, "Frequent use of road by children", false),

        )
        return mixedSigns
    }



}